# # test_connection.py
# import pymysql
#
# try:
#     connection = pymysql.connect(
#         host='95.217.119.130',
#         user='aieltsir_oprt',
#         password='$1OwukktWWC0',
#         database='aieltsir_ddb'
#     )
#     print("Connection successful")
# except Exception as e:
#     print(f"Error connecting to the database: {e}")
# finally:
#     connection.close()
